### ISSUE TITLE
Git Clone Error

### ISSUE THREAD

**Issue by baluver2k2** [odpi/OpenDS4All#103]
Invalid path: assets/data/scripts-autoload-data/data-wrangling/finance.yahoo.com/cryptocurrencies/?count=100&offset=0
Invalid path: assets/data/scripts-autoload-data/data-wrangling/finance.yahoo.com/cryptocurrencies/?count=100&offset=0

**Comment by zackives** [comment]
Can you please specify your operating system?  e.g., is this on Windows?

**Comment by baluver2k2** [comment]
> Can you please specify your operating system? e.g., is this on Windows?

Windows 10

**Comment by Frenchhorn005** [comment]
Nobody else reported the issue and no response for 20 days. Closing issue. Please reopen issue is it still needs attention.
