### ISSUE TITLE
CU Leeds School of Business - Colorado University

### ISSUE THREAD

**Issue by jiportilla** [odpi/OpenDS4All#133]
As faculty, I would like to bring this program to the Leeds School of Business at Colorado University , Boulder, CO USA

https://www.colorado.edu/business/

I will reach out to Ana & Andre to follow up.

Ivan Portilla
Jesus.Portilla@colorado.edu
ivanp@us.ibm.com

**Comment by Frenchhorn005** [comment]
Ivan, thanks for reaching out. I accepted the invitation.

Looking forward to talking with you.

Andre
