### ISSUE TITLE
Should just the slides cover a 50 min lecture ?

### ISSUE THREAD

**Issue by sumedhvdatar** [odpi/OpenDS4All#252]
The contribution guidelines says that each topic must have 30 slides. If the contents just for the slides is less than 50 mins , can we go through the jupyter notebook and explain ?

**Comment by Frenchhorn005** [comment]
Hi, thanks for the message. The suggestion is that each slide deck should have at least 30 slides and cover a 50min lecture. Usually you need at least one additional hour to cover the Jupyter Notebook. These are just recommendations and not hard and fast rules. Obviously, you can adjust the times to suit your class schedule and program. Hope this clarification helps.

Andre de Waal
OpenDS4All Technical Steering Committee Chairperson
