### ISSUE TITLE
Transfer Learning for Computer Vision

### ISSUE THREAD

**Issue by sumedhvdatar** [odpi/OpenDS4All#256]
This module gives details about the concept of transfer learning, transfer learning for computer vision based applications and hands on transfer learning with keras and tensorflow. It also talks about pre-trained models and imagenet dataset.

**Comment by Frenchhorn005** [comment]
Hi sumedhvdatar, if you are the author of a module on transfer learning and you want to submit it to OpenDS4All for incorporation into the repository, please contact me and I will explain the submission and evaluation criteria and the process.

Andre de Waal
OpenDS4All Technical Steering Committee Chairperson

**Comment by sumedhvdatar** [comment]
Sure, I need your email . Can you share your email id.. Thanks

**Comment by Frenchhorn005** [comment]
My e-mail address is andre.dewaal@ibm.com. Please contact me directly at that e-mail address if you are interested in contributing to OpenDS4All. I add a link to the contribution guidelines.

https://github.com/odpi/OpenDS4All/blob/master/CONTRIBUTING.md

**Comment by Frenchhorn005** [comment]
Will work with Sumedh on contributing to OpenDS4All.

Andre de Waal
