### ISSUE TITLE
What about Binder

### ISSUE THREAD

**Issue by ericvd-ucb** [odpi/OpenDS4All#63]
Hi there
This is an amazing awesome effort
I think it would be helpful to put binder links in the readmes!
https://mybinder.org/v2/gh/odpi/OpenDS4All/0e677a48e85d74f8de5b9700b1836eb49d58369b

Seems like you didnt mention Binder at all in the resources page?

**Comment by zackives** [comment]
Great point, yes we should do this!

**Comment by Frenchhorn005** [comment]
Will look into that. Thank you for the suggestion.

**Comment by choldgraf** [comment]
+1 from me - I'd love for Binder to be featured here. As a 💯 open source / community-driven project that runs equally across all cloud vendors, I think it aligns well with the open source goals of this project.

**Comment by leestott** [comment]
+ 1 for me also Binder is pretty key in Data Science.https://jupyter.org/binder

**Comment by Frenchhorn005** [comment]
Thanks for the comments and confirming that we need to look at Binder. It is high on our priority list of things to do to improve the usability of the contents in the repository.

**Comment by zackives** [comment]
PR #94 should allow Binder to be used with almost all of the notebooks, with the exception of those requiring Apache Spark.  The latter will require some work on setting up a Docker container for Binder.

**Comment by zackives** [comment]
Additional functionality will be developed as part of enhancement #95
