### ISSUE TITLE
Ethics slide link is broken

### ISSUE THREAD

**Issue by esuess** [odpi/OpenDS4All#87]
I am very interested in seeing the slides for the Ethics presentation.  The link is broken.

**Comment by misterhay** [comment]
The slides are at https://github.com/odpi/OpenDS4All/blob/master/opends4all-resources/opends4all-ethics/ETHICS-Ethics-Privacy-Fairness-basic.pptx

The link needs to be updated in https://github.com/odpi/OpenDS4All/blob/master/opends4all-resources/opends4all-ethics/README.md.

**Comment by misterhay** [comment]
The slides are at https://github.com/odpi/OpenDS4All/blob/master/opends4all-resources/opends4all-ethics/ETHICS-Ethics-Privacy-Fairness-basic.pptx

I've submitted a pull request to update the readme file: https://github.com/odpi/OpenDS4All/pull/90

**Comment by zackives** [comment]
Thanks for fixing!
